plugins: embedart lastgenre fetchart chroma scrub
art_filename: folder
threaded: no
per_disc_numbering: yes
id3v23: no
asciify_paths: true

match:
    strong_rec_thresh: 0.10 # 0.04
    medium_rec_thresh: 0.25 # 0.25
    rec_gap_thresh: 0.25 # 0.25
    max_rec:
        missing_tracks: medium # medium
        unmatched_tracks: medium # medium
        track_length: medium
        mediums: medium
        year: medium
        media: medium
        track_index: medium
    distance_weights:
        source: 2.0 # 2.0
        artist: 3.0 # 3.0
        album: 3.0 # 3.0
        media: 1.0 # 1.0
        mediums: 9.0 # 1.0
        year: 9.0 # 1.0
        country: 0.5 # 0.5
        label: 0.5 # 0.5
        catalognum: 0.5 # 0.5
        albumdisambig: 0.5 # 0.5
        album_id: 5.0 # 5.0
        tracks: 2.0 # 2.0
        missing_tracks: 9.0 # 0.9
        unmatched_tracks: 9.0 # 0.6
        track_title: 3.0 # 3.0
        track_artist: 2.0 # 2.0
        track_index: 9.0 # 1.0
        track_length: 9.0 # 2.0
        track_id: 5.0 # 5.0
    preferred:
        countries: [] # []
        media: [] # []
        original_year: yes # no
    ignored: ['missing_tracks', 'track_length', 'unmatched_tracks', 'mediums', 'year', 'track_index'] # []
    required: ['year', 'album', 'artist'] # []
    ignored_media: [] # []
    ignore_data_tracks: yes # yes
    ignore_video_tracks: yes # yes
    track_length_grace: 1 # 10
    track_length_max: 1 # 30

paths:
    default: $disc$track - $title
    singleton: $disc$track - $title
    comp: $disc$track - $title
    albumtype_soundtrack: $disc$track - $title
        
import:
    write: yes
    copy: no
    move: no
    resume: ask
    incremental: no
    quiet_fallback: skip
    timid: no
    duplicate_action: skip
    languages: ['en']
    group_albums: no

musicbrainz:
    host: musicbrainz.org
    ratelimit: 1
    searchlimit: 20
    
chroma:
    auto: yes

embedart:
    auto: yes
    
fetchart:
    auto: yes
    cautious: true
    enforce_ratio: yes
    sources: filesystem

lastgenre:
    auto: yes
    force: yes
    count: 5
    separator: '; '
    prefer_specific: no

scrub:
    auto: yes
