#!/bin/bash
#####################################################################################################
#                                     Lidarr Automated Downloader                                   #
#                                       Credit: RandomNinjaAtk                                      #
#####################################################################################################
#                                           Instructions                                            #
#                                                                                                   #
#  1. Configure the settings below                                                                  #
#  2. Execute script from linux cli with the following command:                                     #
#     bash lidarr-automated-downloader.bash                                                        #
#####################################################################################################

############ Paths
downloaddir="/downloads/dlclient" # Dl client download directory location
PathToDLClient="/path/to/dlclient" # Path to DL client directory (deemix)
LidarrImportLocation="/downloads/lidarr-import" # Temporary location that completed downloads are moved to before lidarr attempts to match and import

############ Lidarr Settings
LidarrUrl="http://127.0.0.1:8686" # Set domain or IP to your Lidarr instance including port. If using reverse proxy, do not use a trailing slash. Ensure you specify http/s.
LidarrApiKey="08d108d108d108d108d108d108d108d1" # Lidarr API key.

############ Musicbrainz
musicbrainzurl="http://musicbrainz.org" # Change to use different musicbrainz mirror...
ratelimit=1 # musicbrainz rate limit, musicbrainz allows only 1 connection per second, max setting is 10

############ Beets File locaitons
BeetConfig="beets-config.yaml"
BeetLibrary="beets-library.blb"

############ Download Client Settings
python="python" # command to execute python 3 applications/scripts (for ubuntu, use: python3)
DownloadMode="Audio" # Both or Audio or Video :: "Both" downloads audio and videos; "Audio" downlods only audio files; "Video" only downloads video files
AudioMode="wanted" # wanted or archive :: wanted mode processes Lidarr Wanted/Cutoff Album lists (TrackUpgrade must be enabled for Cutoff) :: archive mode downloads all albums for an aritst, no lidarr matching is used for importing, keeps everything... WARNING: When using archive mode, do not rename album folders or you will continuely re-download available albums...
TrackUpgrade="false" # true = Enabled :: Upgrades existing tracks to requested format. "wanted" mode is controlled by cutoff album list and "archive" mode is detected automatically. Recommend disabling for archive mode, unless your changing your format.
VerifyTrackCount="true" # true = enabled :: This will verify album track count vs dl track count, if tracks are found missing, it will skip import...
DownLoadArtistArtwork="false" # true = enabled :: Uses Lidarr Artist artwork first and fallsback to Deezer
ImportMode="match" # match or forced or manual :: "match" uses lidarr's matching engine to import; "forced" moves the download into the Lidarr artist directory; "manual" downloads are left in the temp import directory for you to manual import

############ File Options
quality="FLAC" # SET TO: OPUS or AAC or FDK-AAC or MP3 or ALAC or FLAC :: Set desired library format (Flac is converted for opus, aac, and alac types)
ConversionBitrate="320" # Set to desired bitrate when converting to OPUS/AAC format types
ReplaygainTagging="TRUE" # TRUE = ENABLED, adds replaygain tags for compatible players (FLAC ONLY)
FilePermissions="666" # Based on chmod linux permissions
FolderPermissions="777" # Based on chmod linux permissions
TagWithBeets="false" # true = enabled :: enable beet tagging to improve matching accuracy, requires beets installation and beets file path configuration
RequireBeetsMatch="false" # true = enabled :: skips importing files that could not be matched using beets
RequireQuality="false" # true = enabled :: skips importing files that do not match quality settings

############ Script Options
amount="1000000000" # Maximum: 1000000000 :: Number of wanted albums to look for....

############ Music Video Options
VideoPath="/path/to/vides" # Location of music videos
YoutubeDL="/usr/local/bin/youtube-dl" # Path to youtube-dl application, executed using python
CountryCode="US" # set the country code for preferred video matching, uses Musicbrainz Country Codes
RequireVideoMatch="true" # true = enabled :: Only keep videos that could be matched to a Musicbrainz music track.
videoformat="--format bestvideo[vcodec!*=av01]+bestaudio[ext=m4a]" # For guidence, please see youtube-dl documentation
videofilter="live" # This will filter out videos Matching MusicBrainz secondary release type and album disambiguation (single word only)
