#!/bin/bash
#####################################################################################################
#                                     Lidarr Automated Downloader                                   #
#                                       Credit: RandomNinjaAtk                                      #
#####################################################################################################
#                                           Instructions                                            #
#                                                                                                   #
#  1. Configure the settings below                                                                  #
#  2. Execute script from linux cli with the following command:                                     #
#     bash lidarr-automated-downloader.bash                                                        #
#####################################################################################################

############ Paths
downloaddir="/downloads/dlclient" # Dl client download directory location
PathToDLClient="/path/to/dlclient" # Path to DL client directory (d-fi)
LidarrImportLocation="/downloads/lidarr-import" # Temporary location that completed downloads are moved to before lidarr attempts to match and import

############ Lidarr Settings
LidarrUrl="http://127.0.0.1:8686" # Set domain or IP to your Lidarr instance including port. If using reverse proxy, do not use a trailing slash. Ensure you specify http/s.
LidarrApiKey="08d108d108d108d108d108d108d108d1" # Lidarr API key.

############ Beets File locaitons
BeetConfig="beets-config.yaml"
BeetLibrary="beets-library.blb"

############ Download Client Settings
ARLToken="" # User token for dl client
VerifyTrackCount="true" # true = enabled :: This will verify album track count vs dl track count, if tracks are found missing, it will skip import...
DownLoadArtistArtwork="false" # true = enabled :: Uses Lidarr Artist artwork first and fallsback to Deezer

############ File Options
quality="FLAC" # SET TO: OPUS or AAC or FDK-AAC or MP3 or ALAC or FLAC :: Set desired library format (Flac is converted for opus, aac, and alac types)
ConversionBitrate="320" # Set to desired bitrate when converting to OPUS/AAC/MP3 format types
ReplaygainTagging="TRUE" # TRUE = ENABLED, adds replaygain tags for compatible players (FLAC ONLY)
FilePermissions="666" # Based on chmod linux permissions
FolderPermissions="777" # Based on chmod linux permissions
TagWithBeets="false" # true = enabled :: enable beet tagging to improve matching accuracy, requires beets installation and beets file path configuration
RequireBeetsMatch="false" # true = enabled :: skips importing files that could not be matched using beets
RequireQuality="false" # true = enabled :: skips importing files that do not match quality settings
############ Script Options
amount="1000000000" # Maximum: 1000000000 :: Number of wanted albums to look for....

